# Use official Node.js 18 image as the base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Expose port 5173
EXPOSE 5173

# Command to start the application in development mode with the --host option
CMD ["npm", "run", "dev", "--", "--host"]